### ISSUE TITLE
Fetching course id for user

### ISSUE THREAD

**Issue by RouNNdeL** [CyberBot-Elka/cyber-bot-python#1]
When a new user is inserted into the DB by the Messenger Bot it doesn't fetch any USOS API data, except setting the `access_token` and `access_token_secret`. On a cron run of python detect those users and get their `course_id`.

**Comment by 8ru73u5** [comment]
This should be done directly after inserting user into the DB. Better solution would be fetching `course_id` by the Messenger Bot and inserting it along with other user data.
