### ISSUE TITLE
Records for subjects and courses

### ISSUE THREAD

**Issue by RouNNdeL** [CyberBot-Elka/cyber-bot-python#3]
Create tables and insert records for all supported courses (`Informatyka` and `Cyberbezpieczeństwo`, for now) and their subjects. Preferably automate the process with a python script which loads them from the USOS API.

**Comment by 8ru73u5** [comment]
In order to obtain course information you need to call `services/groups/participant` and specify fields you want to include in the output. Sample output:

```json
{
   "class_type": {
      "pl": "Wykład",
      "en": "lectures"
   },
   "course_name": {
      "pl": "Algorytmy i programowanie 1",
      "en": "Algorithms and Programming 1"
   },
   "course_id": "103A-CBxxx-ISP-APRO1",
   "term_id": "2019Z",
   "class_type_id": "WYK"
}
```
